apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: container-monitor
  labels:
    app: container-monitor
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: container-monitor
      labels:
        app: container-monitor
    spec:
      template:
        metadata:
          name: container-monitor
          labels:
            app: container-monitor
        spec:
          containers:
          - name: container-monitor
            image: softleader/container-monitor
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /var/softleader_home/container_monitor/
              name: container-monitor-volume
            - mountPath: "/var/run/docker.sock"
              name: docker-socket
          volumes:
          - name: docker-socket
            persistentVolumeClaim:
              claimName: docker-socket-claim
          - name: container-monitor-volume
            hostPath:
              path: /data
              type: Directory
          restartPolicy: Never